version: '3.8'

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"       # En az Windows 10 istiyoruz
      KVM: "N"            # KVM hatasını bypass etmek için şart
      RAM_SIZE: "4G"      # Win 10 için 2G çok az, Codespace'i zorlamadan 4G veriyoruz
      CPU_CORES: "2"
      DISK_SIZE: "20G"    # Win 10 kurulumu için diski 20GB yaptık
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
    volumes:
      - win_data:/storage
    stop_grace_period: 2m

volumes:
  win_data: